- name: restart_apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: update_html_file
  tags: apache,httpd,centos
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
