- name: install unzip
  package:
    name: unzip

- name:  install terraform
  unarchive:
    src: https://108.139.47.112/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
