---
- hosts: apps
  become: true
  tasks:
  - name: install apache2 and php packages and update repository index
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages and upate repository index
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd service
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: enable port 80
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    when: ansible_distribution == "CentOS"

