---
- hosts: all
  become: true
  tasks:
  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: apps
  become: true
  tasks:
  - name: install apache and php packages on  Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages on CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd service on CentOS
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: enable port 80 on CentOS
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    when: ansible_distribution == "CentOS"

