- name: install apache and php packages
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
  when: ansible_distribution == "CentOS"
  notify: update_html_file

- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin (CentOS)
  tags: apache,http,centos
  lineinfile:
    path: /var/www/html/index.html
    regexp: ServerAdmin
    line: ServerAdmin somebody@somewhere.edu
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: enable port 80 on CentOS
  tags: apache,httpd,centos
  ansible.posix.firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled
  when: ansible_distribution == "CentOS"
  register: firewalld

- name: reload firewalld.service
  tags: apache,httpd,centos
  systemd:
    name: firewalld
    state: reloaded
  when: firewalld.changed
